---@param c Quietink.Palette
---@param cfg Quietink.Config
return function(c, cfg)
  local s = cfg.styles

  return {
    -- base syntax (legacy, still used as fallback)
    Comment = vim.tbl_extend("force", { fg = c.comment, italic = false }, s.comments),
    Constant = vim.tbl_extend("force", { fg = c.const_ }, s.constants),
    String = vim.tbl_extend("force", { fg = c.string }, s.strings),
    Character = { fg = c.string },
    Number = vim.tbl_extend("force", { fg = c.const_ }, s.constants),
    Boolean = vim.tbl_extend("force", { fg = c.const_ }, s.constants),
    Float = vim.tbl_extend("force", { fg = c.const_ }, s.constants),
    Identifier = { fg = c.fg },
    Function = vim.tbl_extend("force", { fg = c.func }, s.functions),
    Statement = vim.tbl_extend("force", { fg = c.keyword }, s.keywords),
    Conditional = vim.tbl_extend("force", { fg = c.keyword }, s.keywords),
    Repeat = vim.tbl_extend("force", { fg = c.keyword }, s.keywords),
    Label = { fg = c.keyword },
    Operator = { fg = c.punct },
    Keyword = vim.tbl_extend("force", { fg = c.keyword }, s.keywords),
    Exception = vim.tbl_extend("force", { fg = c.keyword }, s.keywords),
    PreProc = { fg = c.keyword },
    Include = { fg = c.keyword },
    Define = { fg = c.keyword },
    Macro = { fg = c.keyword },
    Type = { fg = c.type },
    StorageClass = { fg = c.keyword },
    Structure = { fg = c.type },
    Typedef = { fg = c.type },
    Special = { fg = c.tag },
    SpecialChar = { fg = c.tag },
    Tag = { fg = c.tag },
    Delimiter = { fg = c.punct },
    SpecialComment = { fg = c.comment, italic = false },
    Underlined = { underline = true },
    Ignore = { fg = c.fg_dim },
    Error = { fg = c.danger },
    Todo = { fg = c.bg, bg = c.warning, bold = true },

    -- treesitter
    ["@comment"] = { link = "Comment" },
    ["@string"] = { link = "String" },
    ["@string.escape"] = { fg = c.tag },
    ["@string.regex"] = { fg = c.tag },
    ["@string.special"] = { fg = c.tag },
    ["@character"] = { link = "Character" },
    ["@number"] = { link = "Number" },
    ["@boolean"] = { link = "Boolean" },
    ["@float"] = { link = "Float" },
    ["@constant"] = { link = "Constant" },
    ["@constant.builtin"] = { fg = c.const_, italic = false },
    ["@constant.macro"] = { fg = c.const_ },

    ["@function"] = { link = "Function" },
    ["@function.builtin"] = vim.tbl_extend("force", { fg = c.func, italic = false }, s.functions),
    ["@function.call"] = { link = "Function" },
    ["@function.macro"] = { link = "Function" },
    ["@function.method"] = { link = "Function" },
    ["@function.method.call"] = { link = "Function" },
    ["@constructor"] = { fg = c.type },
    ["@parameter"] = { fg = c.fg },

    ["@keyword"] = { link = "Keyword" },
    ["@keyword.function"] = vim.tbl_extend("force", { fg = c.keyword }, s.keywords),
    ["@keyword.operator"] = { fg = c.keyword },
    ["@keyword.return"] = vim.tbl_extend("force", { fg = c.keyword }, s.keywords),
    ["@keyword.import"] = { fg = c.keyword },
    ["@keyword.conditional"] = { link = "Conditional" },
    ["@keyword.repeat"] = { link = "Repeat" },
    ["@keyword.exception"] = { link = "Exception" },

    ["@operator"] = { link = "Operator" },
    ["@punctuation.delimiter"] = { link = "Delimiter" },
    ["@punctuation.bracket"] = { fg = c.punct },
    ["@punctuation.special"] = { fg = c.tag },

    ["@variable"] = { fg = c.fg },
    ["@variable.builtin"] = { fg = c.fg_dim, italic = false },
    ["@variable.parameter"] = { fg = c.fg },
    ["@variable.member"] = { fg = c.fg },

    ["@type"] = { link = "Type" },
    ["@type.builtin"] = { fg = c.type, italic = false },
    ["@type.definition"] = { link = "Type" },
    ["@attribute"] = { fg = c.tag },
    ["@property"] = { fg = c.fg },
    ["@field"] = { fg = c.fg },

    ["@tag"] = { link = "Tag" },
    ["@tag.attribute"] = { fg = c.type },
    ["@tag.delimiter"] = { fg = c.punct },

    ["@module"] = { fg = c.type },
    ["@namespace"] = { fg = c.type },
    ["@label"] = { link = "Label" },
    ["@markup.strong"] = { bold = true },
    ["@markup.italic"] = { italic = true },
    ["@markup.strikethrough"] = { strikethrough = true },
    ["@markup.underline"] = { underline = true },
    ["@markup.heading"] = { fg = c.emphasis, bold = true },
    ["@markup.link"] = { fg = c.info, underline = true },
    ["@markup.link.url"] = { fg = c.info, underline = true },
    ["@markup.raw"] = { fg = c.string },
    ["@markup.list"] = { fg = c.punct },
    ["@comment.todo"] = { link = "Todo" },
    ["@comment.error"] = { fg = c.bg, bg = c.danger },
    ["@comment.warning"] = { fg = c.bg, bg = c.warning },
    ["@comment.note"] = { fg = c.bg, bg = c.info },

    ["@diff.plus"] = { link = "DiffAdd" },
    ["@diff.minus"] = { link = "DiffDelete" },
    ["@diff.delta"] = { link = "DiffChange" },

    -- LSP semantic tokens
    ["@lsp.type.class"] = { link = "Type" },
    ["@lsp.type.interface"] = { link = "Type" },
    ["@lsp.type.enum"] = { link = "Type" },
    ["@lsp.type.enumMember"] = { link = "Constant" },
    ["@lsp.type.struct"] = { link = "Type" },
    ["@lsp.type.parameter"] = { fg = c.fg },
    ["@lsp.type.property"] = { fg = c.fg },
    ["@lsp.type.variable"] = { fg = c.fg },
    ["@lsp.type.namespace"] = { link = "Type" },
    ["@lsp.type.function"] = { link = "Function" },
    ["@lsp.type.method"] = { link = "Function" },
    ["@lsp.type.decorator"] = { fg = c.tag },
    ["@lsp.typemod.function.readonly"] = { link = "Function" },
    ["@lsp.typemod.variable.readonly"] = { fg = c.const_ },
    ["@lsp.typemod.variable.globalScope"] = { fg = c.fg },

    DiagnosticError = { fg = c.danger },
    DiagnosticWarn = { fg = c.warning },
    DiagnosticInfo = { fg = c.info },
    DiagnosticHint = { fg = c.hint },
    DiagnosticOk = { fg = c.success },
    DiagnosticUnderlineError = { undercurl = true, sp = c.danger },
    DiagnosticUnderlineWarn = { undercurl = true, sp = c.warning },
    DiagnosticUnderlineInfo = { undercurl = true, sp = c.info },
    DiagnosticUnderlineHint = { undercurl = true, sp = c.hint },
    DiagnosticVirtualTextError = { fg = c.danger, bg = c.bg_alt },
    DiagnosticVirtualTextWarn = { fg = c.warning, bg = c.bg_alt },
    DiagnosticVirtualTextInfo = { fg = c.info, bg = c.bg_alt },
    DiagnosticVirtualTextHint = { fg = c.hint, bg = c.bg_alt },
    DiagnosticSignError = { fg = c.danger },
    DiagnosticSignWarn = { fg = c.warning },
    DiagnosticSignInfo = { fg = c.info },
    DiagnosticSignHint = { fg = c.hint },
    DiagnosticFloatingError = { fg = c.danger },
    DiagnosticFloatingWarn = { fg = c.warning },
    DiagnosticFloatingInfo = { fg = c.info },
    DiagnosticFloatingHint = { fg = c.hint },

    LspReferenceText = { bg = c.sel },
    LspReferenceRead = { bg = c.sel },
    LspReferenceWrite = { bg = c.sel },
    LspSignatureActiveParameter = { fg = c.emphasis, bold = true },
    LspCodeLens = { fg = c.fg_dim, italic = true },
    LspInlayHint = { fg = c.fg_dim, bg = c.bg_alt, italic = true },
  }
end
